### ISSUE TITLE
Switch packages over to using ITensorMPS.jl

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensorMPS.jl#3]
For example:
 - [ ] [ITensorAFQMC.jl](https://github.com/mtfishman/ITensorAFQMC.jl) - private and unregistered
 - [x] [ITensorAGP.jl](https://github.com/ITensor/ITensorAGP.jl) - unregistered (https://github.com/ITensor/ITensorAGP.jl/pull/5)
 - [x] [ITensorChemistry.jl](https://github.com/mtfishman/ITensorChemistry.jl) - unregistered (https://github.com/mtfishman/ITensorChemistry.jl/pull/12)
 - [x] [ITensorCorrelators.jl](https://github.com/ITensor/ITensorCorrelators.jl) - unregistered (https://github.com/ITensor/ITensorCorrelators.jl/pull/3)
 - [x] [ITensorGaussianMPS.jl](https://github.com/ITensor/ITensorGaussianMPS.jl) (https://github.com/ITensor/ITensorGaussianMPS.jl/pull/6)
 - [x] [ITensorGLMakie.jl](https://github.com/ITensor/ITensorGLMakie.jl) (https://github.com/ITensor/ITensorGLMakie.jl/pull/6) **[Assigned to Miles]**
 - [x] [ITensorGPU.jl](https://github.com/ITensor/ITensorGPU.jl) (https://github.com/ITensor/ITensorGPU.jl/pull/7)
 - [x] [ITensorInfiniteMPS.jl](https://github.com/ITensor/ITensorInfiniteMPS.jl) (https://github.com/ITensor/ITensorInfiniteMPS.jl/pull/83)
 - [x] [ITensorMakie.jl](https://github.com/ITensor/ITensorMakie.jl) (no update required) **[Assigned to Miles]**
 - [ ] [ITensorMPOCompression.jl](https://github.com/JanReimers/ITensorMPOCompression.jl) (started in https://github.com/JanReimers/ITensorMPOCompression.jl/pull/7)
 - [x] [ITensorMPOConstruction.jl](https://github.com/ITensor/ITensorMPOConstruction.jl) - unregistered (https://github.com/ITensor/ITensorMPOConstruction.jl/pull/15)
 - [x] [ITensorNetworks.jl](https://github.com/ITensor/ITensorNetworks.jl) (https://github.com/ITensor/ITensorNetworks.jl/pull/172)
 - [x] [ITensorParallel.jl](https://github.com/ITensor/ITensorParallel.jl) - unregistered (https://github.com/ITensor/ITensorParallel.jl/pull/22)
 - [x] [ITensorQTT.jl](https://github.com/mtfishman/ITensorQTT.jl) - unregistered (https://github.com/mtfishman/ITensorQTT.jl/pull/11)
 - [x] [ITensorTDVP.jl](https://github.com/ITensor/ITensorTDVP.jl) (upgrade guide in https://github.com/ITensor/ITensorTDVP.jl/pull/73)
 - [x] [ITensorUnicodePlots.jl](https://github.com/ITensor/ITensorUnicodePlots.jl) (https://github.com/ITensor/ITensorUnicodePlots.jl/pull/3) **[Assigned to Miles]**
 - [x] [ITensorVisualizationBase.jl](https://github.com/ITensor/ITensorVisualizationBase.jl) (https://github.com/ITensor/ITensorVisualizationBase.jl/pull/4) **[Assigned to Miles]**
 - [ ] [PastaQ.jl](https://github.com/GTorlai/PastaQ.jl) (started in https://github.com/GTorlai/PastaQ.jl/pull/309)

**Comment by emstoudenmire** [comment]
Best I can tell, no code in `ITensorMakie.jl` depends on `ITensorMPS`. So we can mark that one completed.

**Comment by mtfishman** [comment]
This is nearly complete, `ITensorAFQMC.jl` is private and not very functional so isn't urgent to update, `ITensorMPOCompression.jl` has a pending PR, and `PastaQ.jl` has a pending PR which is hitting some issues that is very likely not directly caused by `ITensorMPS.jl`.

@emstoudenmire what's the status of `ITensorQTT.jl`? Can we take a minimal path to upgrading it to using `ITensorMPS.jl` now that #7 is complete?

**Comment by emstoudenmire** [comment]
Good reminder. Now that ITensorMPS is updated, ITensorQTT can access all the types and methods it needs again, so tests are passing and I just made an ITensorQTT PR here: https://github.com/mtfishman/ITensorQTT.jl/pull/11

The biggest change is that I deleted `ITensorQTT.linsolve` since it's essentially the same as ITensorTDVP's linsolve (since it has the same signature it was causing a warning, otherwise I might have just left it alone).

**Comment by mtfishman** [comment]
Ok this is implemented as much as possible right now so I'll close.
